### ISSUE TITLE
Mensaje de error 

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [helio-ecosystem/helio-frontend#14]
Buenas, cuando creo un mapping que no es correcto siempre recibo el error `Http failure response for http://localhost:4567/api/playground?builder=SIoTRxBuilder: 500 Server Error` en lugar de un error descriptivo

**Comment by AndreaCimminoArriaga** [comment]
En realidad tras probar no se si este mensaje es cosa del helio-rest o del front-end, cuando he mandado mappings que tenian errores por otros motivos si que he recibido los errores del helio-rest

**Comment by EmilioCrespoPeran** [comment]
Voy a echarle un vistazo porque quiza sea fallo de la conectividad del helio-rest con el frontend y asi, si lo soluciono te envio la forma de proceder por si ademas resuelve tambien los problemas de conexion en el dominio

**Comment by EmilioCrespoPeran** [comment]
He estado mirando sin exito, te dejo este docker-compose.yml con ambos docker: el normal y playground para ver si te funciona. Le he puesto a drede el networking por si acaso, pero deberia de ser lo mismo

```yml
version: '2'
services:
  helio-rest:
    image: acimmino/helio-rest:latest
    volumes: 
      - type: volume
        source: helio-db
        target: /helio/app
        volume: {}
    ports:
      - "4567:4567"
    networks:
      - helio-ecosystem-network

  frontend:
    image: emiliocrespoperan/helio-frontend:latest
    depends_on:
      - helio-rest
    ports:
      - "4201:80"
    networks:
      - helio-ecosystem-network

  playground:
    image: emiliocrespoperan/helio-frontend-playground:latest
    depends_on:
      - helio-rest
    ports:
      - "4202:80"
    networks:
      - helio-ecosystem-network
      
volumes:
  helio-db:
    name: helio-db

networks: 
  helio-ecosystem-network:
```

**Comment by AndreaCimminoArriaga** [comment]
Si, he estado haciendo pruebas y es por un tema de proxy. ¿Podríamos indicar por parámetro el dominio donde esta el helio backend?, para que no se llame siempre a localhost. Esto creo que podría resolver el problema y es facil pasar parametros a traves de una receta de docker

**Comment by EmilioCrespoPeran** [comment]
Voy a investigarlo para que funcione de esa manera

**Comment by EmilioCrespoPeran** [comment]
Acabo de actualizar la versión para que acepte variables de entorno desde docker, prueba el siguiente docker-compose 

```yml
version: '2'
services:
  helio-rest:
    image: acimmino/helio-rest:latest
    volumes: 
      - type: volume
        source: helio-db
        target: /helio/app
        volume: {}
    ports:
      - "4567:4567"

  frontend:
    image: emiliocrespoperan/helio-frontend:latest
    depends_on:
      - helio-rest
    ports:
      - "4201:80"
      

  playground:
    image: emiliocrespoperan/helio-frontend:latest
    depends_on:
      - helio-rest
    ports:
      - "4202:80"
    environment:
      - HELIO_REST_HOST=http://localhost:4567
      - HELIO_MODE=PLAYGROUND
      
volumes:
  helio-db:
    name: helio-db

```

Te dejo la información actualizada en el fichero [README.MD](https://github.com/helio-ecosystem/helio-frontend/blob/main/README.md) y si esta todo bien, cerramos la issue.
