### ISSUE TITLE
Cambiar docker-compose.yml en el README.md

### ISSUE THREAD

**Issue by jucanbe** [helio-ecosystem/helio-frontend#26]
El primer yml debería ser:

```yml
version: '3'
services:
  helio-publisher:
    image: acimmino/helio-rest:latest
    volumes: 
      - ./local/:/usr/src/app/local/
      - ./db/:/usr/src/app/db/
    ports:
      - "4567:4567"
  frontend:
    image: emiliocrespoperan/helio-frontend:latest
    depends_on:
      - helio-publisher <- cambiar esta línea
    ports:
      - "4201:80"
 ```

El segundo yml debería ser:

```yml
version: '3'
services:
  helio-publisher:
    image: acimmino/helio-rest:latest
    volumes: 
      - ./local/:/usr/src/app/local/
      - ./db/:/usr/src/app/db/
    ports:
      - "4567:4567"
  frontend:
    image: emiliocrespoperan/helio-frontend:latest
    depends_on:
      - helio-publisher
    ports:
      - "4201:80"
    environment: <- añadir esta línea
      - HELIO_REST_HOST=http://localhost:4567
      - HELIO_MODE=PLAYGROUND
```
